In [5]:
!pip install numpy

In [3]:
import numpy as np

Aggregating functions

In [4]:
A = np.array([1,2,3,4,5])
print(A)

[1 2 3 4 5]


In [5]:
A.min()

np.int64(1)

In [6]:
A.max()

np.int64(5)

In [7]:
A.sum()

np.int64(15)

In [8]:
A.mean()

np.float64(3.0)

In [9]:
np.median(A)

np.float64(3.0)

Aggregating functions on multi-dimensional arrays

In [10]:
B = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [11]:
B.mean()

np.float64(8.5)

In [12]:
B.mean(axis = 0)

array([ 7.,  8.,  9., 10.])

In [13]:
B.mean(axis = 1)

array([ 2.5,  6.5, 10.5, 14.5])

Broadcasting with a scalar

In [14]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [15]:
arr_2 = np.full((5,1), 10)
arr_3 = np.full((5), 10)
arr_4 = np.full(5, 10)

In [16]:
print(arr_2)
print(arr_2.ndim)

[[10]
 [10]
 [10]
 [10]
 [10]]
2


In [17]:
print(arr_3)
print(arr_3.ndim)

[10 10 10 10 10]
1


In [18]:
print(arr_4)
print(arr_4.ndim)

[10 10 10 10 10]
1


In [19]:
arr+arr_2

array([[11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15],
       [11, 12, 13, 14, 15]])

In [20]:
arr+arr_3

array([11, 12, 13, 14, 15])

In [21]:
arr+arr_4

array([11, 12, 13, 14, 15])

With broadcasting

In [22]:
result = arr + 10
print(result)

[11 12 13 14 15]


In [23]:
arr.shape

(5,)

In [24]:
np.shape(10)

()

Broadcasting with arrays of different shapes

In [25]:
arr_1d = np.array([10, 20, 30])
print(arr_1d)

[10 20 30]


In [26]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [27]:
arr_1d + arr_2d

array([[11, 22, 33],
       [14, 25, 36]])

In [28]:
a = np.array([1,2,3])
b = 2
a*b

array([2, 4, 6])

In [29]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

Make the 4x1 array

In [30]:
a = np.array([[0], 
              [10], 
              [20], 
              [30]])
print(a)

[[ 0]
 [10]
 [20]
 [30]]


# alternative way to make the 4x1 array

In [31]:
a = np.array([0, 10, 20, 30]) 
a = a[:, np.newaxis]
print(a)

[[ 0]
 [10]
 [20]
 [30]]


Make the 1x3 array

In [32]:
b = np.array([1, 2, 3])
print(b)

[1 2 3]


In [33]:
c = a+b
print(c)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


Creating arrays from existing data

Creating an array from a list

In [34]:
import numpy as np 

In [35]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)
print(arr)

[1 2 3 4 5]


Creating an array from multiple lists

In [37]:
row_1 = [1,2,3]
row_2 = [4,5,6]
row_3 = [7,8,9]
arr = np.array([row_1,row_2,row_3])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
col1 = [1,2,3]
col2 = [4,5,6]
col3 = [7,8,9]
arr = np.array([col1,col2,col3]).T
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Creating arrays from a shape or value

Creating an array where all values are x

In [41]:
my_value = 5
size = (3,4)
arr_x = np.full(size ,my_value)
print(arr_x)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [43]:
arr_zero = np.zeros(size)
arr_one = np.ones(size)
print(arr_zero)
print(arr_one)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Creating an array full of random numbers

In [44]:
rows = 2
cols = 3
arr_random = np.random.rand(rows,cols)
print(arr_random)


[[0.48208633 0.36905812 0.74846868]
 [0.70654388 0.3817153  0.8404931 ]]


Creating an array with numbers only on the diagonal

In [46]:
size = 4
diagonal_values= [1,2,3,4]
arr_diagonal = np.diag(diagonal_values)
print(arr_diagonal)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Creating arrays according to a sequence

In [49]:
arr = np.arange(0,1001,1)
print(arr)

[   0    1    2 ...  998  999 1000]


In [51]:
arr = np.arange(1001)
print(arr)

[   0    1    2 ...  998  999 1000]


Arrays with a specified data type

In [54]:
arr_int = np.array(my_list , dtype ="int")
print(arr_int)

[1 2 3 4 5]


In [55]:
arr_float = np.array(my_list , dtype ="float")
print(arr_float)

[1. 2. 3. 4. 5.]


In [56]:
arr_zero_int = np.zeros((2,2), dtype = "float")
print(arr_zero_int)

[[0. 0.]
 [0. 0.]]


Modifying values in an array

In [57]:
print(arr)

[   0    1    2 ...  998  999 1000]


In [59]:
print(arr[0])

0


Array_attributes

In [60]:
import numpy as np 

In [61]:
arr_a = np.array([1.4,2.1,3.2,4.5])
arr_b = np.array([[1,2,3],[4,5,6]])
arr_c = np.array([True,False,True])
print(arr_a)
print(arr_b)
print(arr_c)


[1.4 2.1 3.2 4.5]
[[1 2 3]
 [4 5 6]]
[ True False  True]


In [62]:
print(arr_a.size)

4


In [63]:
print(arr_a.shape)

(4,)


In [64]:
print(arr_a.dtype)

float64


In [65]:
print(arr_b.size)

6


print(arr_b.shape)

In [67]:
print(arr_b.dtype)

int64


In [68]:
print(arr_c.size)

3


In [69]:
print(arr_c.shape)

(3,)


In [70]:
print(arr_c.dtype)

bool


More attributes

In [71]:
print(arr_a.ndim)

1


In [72]:
print(arr_b.ndim)

2


In [73]:
print(arr_c.ndim)

1


Changing the shape of an array, while keeping the contents

In [74]:
import numpy as np

In [77]:
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [78]:
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
print(arr.reshape(3 ,-1))

[[1 2]
 [3 4]
 [5 6]]


In [80]:
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [81]:
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


Inverse: Flattening a multi-dimensional array

In [82]:
reshaped_arr = arr.reshape(3, 2)
flattened = reshaped_arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [83]:
arr.reshape(2,3).flatten()

array([1, 2, 3, 4, 5, 6])

In [84]:
reshaped_arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

Does reshape mutate the array or make a copy?

In [85]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]]


In [86]:
print(arr.shape)

(6,)


In [87]:
reshaped_arr[0,0] = -50
print(reshaped_arr)

[[-50   2]
 [  3   4]
 [  5   6]]


In [88]:
print(arr)

[-50   2   3   4   5   6]


Lesson

In [89]:
arr2 = np .array([[1,2,3],
                 [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [90]:
flattened = arr2.flatten()
print(flattened)

[1 2 3 4 5 6]


In [91]:
flattened[0] = -100
print(flattened)

[-100    2    3    4    5    6]


In [93]:
flattened_with_reshape = arr2.reshape(-1)
print(flattened_with_reshape)

[1 2 3 4 5 6]


In [94]:
flattened_with_reshape[0] = -100
print(flattened_with_reshape)

[-100    2    3    4    5    6]


Sorting vectors

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(10,size=14)
print(arr)

[8 1 7 1 5 7 0 6 5 8 4 5 1 7]


In [4]:
print(arr.sort())

None


In [5]:
arr_b = np.random.randint(10, size =12)
print(arr_b)

[4 8 0 5 4 6 1 3 8 4 1 3]


In [6]:
sorted_arr_b = np.sort(arr_b)
print(sorted_arr_b)

[0 1 1 3 3 4 4 4 5 6 8 8]


In [7]:
print(arr_b)

[4 8 0 5 4 6 1 3 8 4 1 3]


Sorting matrices

In [8]:
matrix_a = np.random.randint(10,size = (4,4))
print(matrix_a)

[[9 5 7 9]
 [5 6 0 0]
 [2 8 7 3]
 [1 3 9 4]]


In [9]:
matrix_a_sort_default = np.sort(matrix_a)
print(matrix_a_sort_default)

[[5 7 9 9]
 [0 0 5 6]
 [2 3 7 8]
 [1 3 4 9]]


In [10]:
matrix_a_sort_axis = np.sort(matrix_a, axis =  -1)
print(matrix_a_sort_axis)

[[5 7 9 9]
 [0 0 5 6]
 [2 3 7 8]
 [1 3 4 9]]


In [11]:
matrix_a_sort_axis = np.sort(matrix_a, axis = 0)
print(matrix_a_sort_axis)

[[1 3 0 0]
 [2 5 7 3]
 [5 6 7 4]
 [9 8 9 9]]


Accessing elements in an array with indexing

In [12]:
import numpy as np

In [13]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[1,1])

6


In [16]:
print(arr[2,3])

12


Slicing

In [18]:
print(arr[1])

[5 6 7 8]


In [19]:
print(arr[0:2])

[[1 2 3 4]
 [5 6 7 8]]


In [20]:
print(arr[:,0:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]]


In [21]:
print(arr[1,0:2])

[5 6]


Negative indexing

In [22]:
print(arr[-1])

[ 9 10 11 12]


In [23]:
print(arr[-2])

[5 6 7 8]


In [24]:
print(arr[:,-1])

[ 4  8 12]


Caution when modifying slices!

In [25]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
my_slice = arr[:, -1]
print(my_slice)

[ 4  8 12]


In [27]:
my_slice[0] = 1000
print(my_slice)

[1000    8   12]


In [28]:
print(arr)

[[   1    2    3 1000]
 [   5    6    7    8]
 [   9   10   11   12]]


In [29]:
print(my_slice.base)

[[   1    2    3 1000]
 [   5    6    7    8]
 [   9   10   11   12]]


In [30]:
slice_copy = arr[:, -1].copy()
print(slice_copy)

[1000    8   12]


In [31]:
slice_copy[1] = 0
print(slice_copy)

[1000    0   12]


Indexing with logical operators

In [35]:
print(arr > 8)

[[False False False  True]
 [False False False False]
 [ True  True  True  True]]


In [36]:
print(arr[arr > 8])

[1000    9   10   11   12]


In [37]:
arr[arr>8] = 8
print(arr)

[[1 2 3 8]
 [5 6 7 8]
 [8 8 8 8]]


In [41]:
compound_condition = (arr % 2 == 1) & (arr > 4)
print(arr[compound_condition])

[5 7]


In [40]:
my_subset = arr[arr<4]
print(my_subset)

[1 2 3]


In [42]:
print(my_subset.base)

None


#Dealing with missing data 

In [43]:
import numpy as np

In [45]:
arr = np.array([[1, 2, np.nan],
                [4, np.nan, 6],
                [7, 8, 9]])
print(np.isnan(arr))

[[False False  True]
 [False  True False]
 [False False False]]


Counting NaN values

In [48]:
print(np.count_nonzero(np.isnan(arr)))

2


In [49]:
True + True + True + False

3

In [50]:
print(np.isnan(arr).sum())

2


Working with NaN values

In [51]:
print(arr.sum())

nan


In [52]:
print(np.nansum(arr))

37.0


In [57]:
print(np.where(np.isnan(arr), 0, arr))

[[1. 2. 0.]
 [4. 0. 6.]
 [7. 8. 9.]]


Joining arrays

In [58]:
import numpy as np

In [60]:
arr1= np.array([1,2,3,4])
arr2= np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [61]:
print(np.hstack((arr1, arr2)))

[1 2 3 4 5 6 7 8]


In [62]:
print(np.vstack((arr1, arr2)))

[[1 2 3 4]
 [5 6 7 8]]


In [63]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr3,arr4))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [64]:
print(np.concatenate((arr3, arr4), axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [65]:
print(np.vstack((arr3, arr4)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [66]:
print(np.hstack((arr3, arr4)))

[[1 2 5 6]
 [3 4 7 8]]


In [67]:
arr4 = np.array([[5, 6], [7, 8]])
print(arr4)

[[5 6]
 [7 8]]


In [68]:
arr5 = np.array([9,10])
print(arr5)

[ 9 10]


print(np.vstack((arr4, arr5)))

In [71]:
arr6 = np.array([9,10,11])
print(arr6)

[ 9 10 11]


Basics operations with array

In [73]:
import numpy as np 

In [74]:
arr_a = np.array([1,2,3,4,5])
arr_b = np.array([6,7,8,9,10])
print(arr_a)
print(arr_b)

[1 2 3 4 5]
[ 6  7  8  9 10]


Arithmetic

Addition

In [78]:
print(arr_a+arr_b)

[ 7  9 11 13 15]


In [79]:
print(np.add(arr_a,arr_b))

[ 7  9 11 13 15]


Subtraction

In [80]:
print(arr_a-arr_b)

[-5 -5 -5 -5 -5]


In [81]:
print(np.subtract(arr_a,arr_b))

[-5 -5 -5 -5 -5]


Multiplication

In [82]:
print(arr_a*arr_b)

[ 6 14 24 36 50]


In [83]:
print(np.multiply(arr_a,arr_b))

[ 6 14 24 36 50]


Division

In [84]:
print(arr_a/arr_b)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [85]:
print(np.divide(arr_a,arr_b))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


Logical operations

In [86]:
print(arr_a > 3)

[False False False  True  True]


In [87]:
print(np.any(arr_a > 3))

True


In [88]:
print(np.all(arr_a > 3))

False


In [89]:
arr_c = np.array([True, True, False, True])
arr_d = np.array([True, False, True, True])
print(arr_c & arr_d)

[ True False False  True]
