In [7]:
import numpy as np

#0-D Array

In [24]:
arr = np.array(50)
print(arr)
print(type(arr))
print(arr.ndim)

50
<class 'numpy.ndarray'>
0


#1-D Array

In [25]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1.ndim)

[1 2 3 4 5]
1


#2-D Array

In [26]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.ndim)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2


#2-D Array

In [27]:
arr3 = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
3


# Accessing Array Elements

In [9]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [17]:
arr1[3]

np.int64(4)

In [13]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
arr2[0,1]

np.int64(2)

In [19]:
arr2[1]

array([5, 6, 7, 8])

In [20]:
arr2[1,1]

np.int64(6)

In [21]:
arr3 = np.array([1,2,3,4,5,6,7])
print(arr3)

[1 2 3 4 5 6 7]


In [24]:
arr3[1:5]

array([2, 3, 4, 5])

In [26]:
arr4 = np.array([1,2,3,4,5,6,7])
print(arr4)

[1 2 3 4 5 6 7]


In [27]:
arr4[4:]

array([5, 6, 7])

In [28]:
arr5 = np.array([1,2,3,4,5,6,7])
print(arr5)

[1 2 3 4 5 6 7]


In [30]:
arr5[:4]

array([1, 2, 3, 4])

# Shape of an Array: shape that returns a tuple with each index having the number of corresponding elements.

In [23]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


Reshape From 1-D to 2-D

In [22]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(6,2)
print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


# Reshape From 1-D to 3-D

In [30]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Iterating Arrays

In [20]:
arr = np.array([1,2,3,4])

for x in arr :
    print(x)

1
2
3
4


# Iterate on the elements of the following 2-D array:

In [19]:
arr = np.array([[1,2,3,4] ,[5,6,7,8]])

for x in arr:
    print(x)

[1 2 3 4]
[5 6 7 8]


# NumPy Joining Array

In [18]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.concatenate((arr1,arr2))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


# Join two 2-D arrays along rows (axis=1):

In [17]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr = np.concatenate((arr1 ,arr2),axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


#Splitting NumPy Arrays
# Splitting is reverse operation of Joining.

In [14]:
arr = np.array([1,2,3,4,5,6])
newarr= np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [38]:
arr = np.array([1,2,3,4,5,6])
newarr= np.array_split(arr,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


#Random

In [39]:
from numpy import random

In [40]:
x = random.randint(100)
print(x)

37


In [41]:
from numpy import random
x = random.rand()
print(x)

0.8513078113035585


In [42]:
from numpy import random
x = random.randint(100,size=(5))
print(x)

[84 87 67 65 85]


In [43]:
from numpy import random
x = random.randint(100,size=(3,5))
print(x)

[[87 56 51  4 63]
 [11 35 49 16 98]
 [13 61 63 81 81]]


In [44]:
from numpy import random
x = random.rand(5)
print(x)

[0.59010344 0.90146718 0.36595913 0.84118175 0.80157277]


In [45]:
from numpy import random
x = random.rand(3,5)
print(x)

[[0.47013588 0.51528224 0.76292344 0.81356701 0.68250791]
 [0.93752674 0.53369441 0.35413232 0.01884227 0.29024459]
 [0.35807281 0.14161611 0.23438075 0.86132874 0.28894529]]


# Sorting methods

In [46]:
import numpy as np 
arr = np.array([9,8,5,3,0])
print(np.sort(arr))

[0 3 5 8 9]


In [48]:
arr = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


#Sort a 2-D array:

In [49]:
arr = np.array([[4,2,8],[3,1,7]])
print(np.sort(arr))

[[2 4 8]
 [1 3 7]]


In [50]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a1D)
print(a2D)
print(a3D)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1 - 1D array creation functions

In [51]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [53]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

2D array creation functions

In [54]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [56]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [59]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [60]:
a = np.array([[1, 2], [3, 4]])
np.diag(a)

array([1, 4])

general ndarray creation functions

In [62]:
import numpy as np
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

Numpyones

In [64]:
import numpy as np
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

Default

In [66]:
import numpy as np
from numpy.random import default_rng
default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [68]:
default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

Indices

In [69]:
import numpy as np
np.indices((3,3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

Replicating, joining, or mutating existing arrays

In [70]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [71]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a = ', a, 'b = ', b)

a =  [1 2 3 4] b =  [2 3]


In [72]:
import numpy as np
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
np.block([[A, B], [C, D]])

array([[ 1.,  1.,  1.,  0.],
       [ 1.,  1.,  0.,  1.],
       [ 0.,  0., -3.,  0.],
       [ 0.,  0.,  0., -4.]])

ADD

In [96]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.add(arr1,arr2)
print(arr)

[ 7  9 11 13 15]


SUBTRACT

In [97]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.subtract(arr1,arr2)
print(arr)

[-5 -5 -5 -5 -5]


MULTIPLY

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.multiply(arr1,arr2)
print(arr)

DIVIDE

In [83]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr = np.divide(arr1,arr2)
print(arr)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


MEAN

In [86]:
arr1 = np.array([1,2,3])
arr = np.mean(arr1)
print(arr)

2.0


MEDIAN

In [87]:
arr1 = np.array([1,2,3])
arr = np.median(arr1)
print(arr)

2.0


STANDARD DEVIATION

In [90]:
arr1 = np.array([1,2,3])
arr = np.std(arr1)
print(arr)

0.816496580927726


VARIANCE

In [91]:
arr1 = np.array([1,2,3])
arr = np.var(arr1)
print(arr)

0.6666666666666666


MINIMUM

In [92]:
arr1 = np.array([1,2,3,4,5,6])
arr = np.min(arr1)
print(arr)

1


MAXIMUM

In [93]:
arr1 = np.array([1,2,3,4,5,6])
arr = np.max(arr1)
print(arr)

6


SUM

In [98]:
arr1 = np.array([1,2,3,4,5,6])
arr = np.sum(arr1)
print(arr)

21


Flatten

In [100]:
arr = np.array([[1,2,3],[4,5,6]])
result = arr.flatten()
print(result)

[1 2 3 4 5 6]


In [101]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
result = arr.flatten()
print(result)

[1 2 3 4 5 6 7 8 9]
